### ISSUE TITLE
Wrong file permissions on some file breaks Foreman import

### ISSUE THREAD

**Issue by clauded** [example42/puppet-logrotate#11]
Some files have wrong file permission : everyone has no read rights (see issue https://github.com/example42/puppet-yum/issues/135 for similar problem).

root@puppet:/etc/puppet/environments/production/modules# ll logrotate/
drwxr-xr-x  6 root   root 4096 Oct 22 13:52 ./
drwxr-xr-x 54 puppet root 4096 Oct 22 13:52 ../
-rw-r-----  1 root   root 1046 Oct 22 13:52 checksums.json
-rw-r--r--  1 root   root  674 Oct 22 13:52 LICENSE
drwxr-xr-x  2 root   root 4096 Oct 22 13:52 manifests/
-rw-r-----  1 root   root  565 Oct 22 13:52 metadata.json
-rw-r--r--  1 root   root  200 Oct 22 13:52 Rakefile
-rw-r--r--  1 root   root 3650 Oct 22 13:52 README.md
drwxr-xr-x  3 root   root 4096 Oct 22 13:52 spec/
drwxr-xr-x  2 root   root 4096 Oct 22 13:52 templates/
drwxr-xr-x  2 root   root 4096 Oct 22 13:52 tests/

root@puppet:/etc/puppet/environments/production/modules# ll logrotate/manifests/
drwxr-xr-x 2 root root  4096 Oct 22 13:52 ./
drwxr-xr-x 6 root root  4096 Oct 22 13:52 ../
-rw-r--r-- 1 root root  1533 Oct 22 13:52 conf.pp
-rw-r--r-- 1 root root  1718 Oct 22 13:52 file.pp
-rw-r----- 1 root root  6689 Oct 22 13:52 init.pp
-rw-r--r-- 1 root root  1122 Oct 22 13:52 params.pp
-rw-r--r-- 1 root root 14357 Oct 22 13:52 rule.pp
-rw-r--r-- 1 root root   567 Oct 22 13:52 spec.pp

**Comment by alvagante** [comment]
Try the newly updated 2.0.17 from the forge

**Comment by clauded** [comment]
Fixed! Thanks.
